<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hMSqnkL' shared service.

return $this->privates['.service_locator.hMSqnkL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'templatesComment' => array('privates', '.errored..service_locator.hMSqnkL.App\\Entity\\TemplatesComment', NULL, 'Cannot autowire service ".service_locator.hMSqnkL": it references class "App\\Entity\\TemplatesComment" but no such service exists.'),
));
