<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6cK97Yc' shared service.

return $this->privates['.service_locator.6cK97Yc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'template' => array('privates', '.errored..service_locator.6cK97Yc.App\\Entity\\Template', NULL, 'Cannot autowire service ".service_locator.6cK97Yc": it references class "App\\Entity\\Template" but no such service exists.'),
));
