<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.9J1BkiM' shared service.

return $this->privates['.service_locator.9J1BkiM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'builder' => array('privates', 'App\\Services\\TemplateServices\\TemplateBuilder', 'getTemplateBuilderService.php', true),
    'mapper' => array('privates', 'App\\Services\\TemplateServices\\TemplateMapper', 'getTemplateMapperService.php', true),
    'template' => array('privates', '.errored..service_locator.9J1BkiM.App\\Entity\\Template', NULL, 'Cannot autowire service ".service_locator.9J1BkiM": it references class "App\\Entity\\Template" but no such service exists.'),
));
