<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..z4nNFu' shared service.

return $this->privates['.service_locator..z4nNFu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'templatesDescription' => array('privates', '.errored..service_locator..z4nNFu.App\\Entity\\TemplatesDescription', NULL, 'Cannot autowire service ".service_locator..z4nNFu": it references class "App\\Entity\\TemplatesDescription" but no such service exists.'),
));
