<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FNv6yIh' shared service.

return $this->privates['.service_locator.FNv6yIh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'builder' => array('privates', 'App\\Services\\ProductServices\\ProductBuilder', 'getProductBuilderService.php', true),
    'mapper' => array('privates', 'App\\Services\\ProductServices\\ProductMapper', 'getProductMapperService.php', true),
    'product' => array('privates', '.errored..service_locator.FNv6yIh.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.FNv6yIh": it references class "App\\Entity\\Product" but no such service exists.'),
));
