<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yT.jmqX' shared service.

return $this->privates['.service_locator.yT.jmqX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'builder' => array('privates', 'App\\Services\\TemplateServices\\TemplateBuilder', 'getTemplateBuilderService.php', true),
    'product' => array('privates', '.errored..service_locator.yT.jmqX.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.yT.jmqX": it references class "App\\Entity\\Product" but no such service exists.'),
));
