<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Nu_dVR0' shared service.

return $this->privates['.service_locator.Nu_dVR0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'info' => array('privates', '.errored..service_locator.Nu_dVR0.App\\Entity\\Info', NULL, 'Cannot autowire service ".service_locator.Nu_dVR0": it references class "App\\Entity\\Info" but no such service exists.'),
));
