<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Controller\\Admin\\CommentController::delete' => array('privates', '.service_locator.hMSqnkL', 'get_ServiceLocator_HMSqnkLService.php', true),
    'App\\Controller\\Admin\\CommentController::new' => array('privates', '.service_locator.yHljX7m', 'get_ServiceLocator_YHljX7mService.php', true),
    'App\\Controller\\Admin\\DescriptionController::delete' => array('privates', '.service_locator..z4nNFu', 'get_ServiceLocator__Z4nNFuService.php', true),
    'App\\Controller\\Admin\\DescriptionController::new' => array('privates', '.service_locator.6cK97Yc', 'get_ServiceLocator_6cK97YcService.php', true),
    'App\\Controller\\Admin\\InfoController::delete' => array('privates', '.service_locator.Nu_dVR0', 'get_ServiceLocator_NuDVR0Service.php', true),
    'App\\Controller\\Admin\\InfoController::new' => array('privates', '.service_locator.6cK97Yc', 'get_ServiceLocator_6cK97YcService.php', true),
    'App\\Controller\\Admin\\OrderController::add' => array('privates', '.service_locator.Cd5c8Xq', 'get_ServiceLocator_Cd5c8XqService.php', true),
    'App\\Controller\\Admin\\OrderController::delete' => array('privates', '.service_locator.VNApzGZ', 'get_ServiceLocator_VNApzGZService.php', true),
    'App\\Controller\\Admin\\OrderController::edit' => array('privates', '.service_locator.Ep7NscA', 'get_ServiceLocator_Ep7NscAService.php', true),
    'App\\Controller\\Admin\\OrderController::show' => array('privates', '.service_locator.VNApzGZ', 'get_ServiceLocator_VNApzGZService.php', true),
    'App\\Controller\\Admin\\ProductController::add' => array('privates', '.service_locator.Zic7e68', 'get_ServiceLocator_Zic7e68Service.php', true),
    'App\\Controller\\Admin\\ProductController::delete' => array('privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true),
    'App\\Controller\\Admin\\ProductController::edit' => array('privates', '.service_locator.FNv6yIh', 'get_ServiceLocator_FNv6yIhService.php', true),
    'App\\Controller\\Admin\\StatusController::delete' => array('privates', '.service_locator.1z5EI7G', 'get_ServiceLocator_1z5EI7GService.php', true),
    'App\\Controller\\Admin\\StatusController::edit' => array('privates', '.service_locator.1z5EI7G', 'get_ServiceLocator_1z5EI7GService.php', true),
    'App\\Controller\\Admin\\StatusController::index' => array('privates', '.service_locator.Hl4ShtN', 'get_ServiceLocator_Hl4ShtNService.php', true),
    'App\\Controller\\Admin\\TemplateController::add' => array('privates', '.service_locator.yT.jmqX', 'get_ServiceLocator_YT_JmqXService.php', true),
    'App\\Controller\\Admin\\TemplateController::delete' => array('privates', '.service_locator.6cK97Yc', 'get_ServiceLocator_6cK97YcService.php', true),
    'App\\Controller\\Admin\\TemplateController::edit' => array('privates', '.service_locator.9J1BkiM', 'get_ServiceLocator_9J1BkiMService.php', true),
    'App\\Controller\\Admin\\TemplateController::more' => array('privates', '.service_locator.6cK97Yc', 'get_ServiceLocator_6cK97YcService.php', true),
    'App\\Controller\\RegistrationController::register' => array('privates', '.service_locator.wyrb61.', 'get_ServiceLocator_Wyrb61_Service.php', true),
    'App\\Controller\\SecurityController::login' => array('privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true),
    'App\\Controller\\TemplateController::show' => array('privates', '.service_locator.6cK97Yc', 'get_ServiceLocator_6cK97YcService.php', true),
    'App\\Controller\\Admin\\CommentController:delete' => array('privates', '.service_locator.hMSqnkL', 'get_ServiceLocator_HMSqnkLService.php', true),
    'App\\Controller\\Admin\\CommentController:new' => array('privates', '.service_locator.yHljX7m', 'get_ServiceLocator_YHljX7mService.php', true),
    'App\\Controller\\Admin\\DescriptionController:delete' => array('privates', '.service_locator..z4nNFu', 'get_ServiceLocator__Z4nNFuService.php', true),
    'App\\Controller\\Admin\\DescriptionController:new' => array('privates', '.service_locator.6cK97Yc', 'get_ServiceLocator_6cK97YcService.php', true),
    'App\\Controller\\Admin\\InfoController:delete' => array('privates', '.service_locator.Nu_dVR0', 'get_ServiceLocator_NuDVR0Service.php', true),
    'App\\Controller\\Admin\\InfoController:new' => array('privates', '.service_locator.6cK97Yc', 'get_ServiceLocator_6cK97YcService.php', true),
    'App\\Controller\\Admin\\OrderController:add' => array('privates', '.service_locator.Cd5c8Xq', 'get_ServiceLocator_Cd5c8XqService.php', true),
    'App\\Controller\\Admin\\OrderController:delete' => array('privates', '.service_locator.VNApzGZ', 'get_ServiceLocator_VNApzGZService.php', true),
    'App\\Controller\\Admin\\OrderController:edit' => array('privates', '.service_locator.Ep7NscA', 'get_ServiceLocator_Ep7NscAService.php', true),
    'App\\Controller\\Admin\\OrderController:show' => array('privates', '.service_locator.VNApzGZ', 'get_ServiceLocator_VNApzGZService.php', true),
    'App\\Controller\\Admin\\ProductController:add' => array('privates', '.service_locator.Zic7e68', 'get_ServiceLocator_Zic7e68Service.php', true),
    'App\\Controller\\Admin\\ProductController:delete' => array('privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true),
    'App\\Controller\\Admin\\ProductController:edit' => array('privates', '.service_locator.FNv6yIh', 'get_ServiceLocator_FNv6yIhService.php', true),
    'App\\Controller\\Admin\\StatusController:delete' => array('privates', '.service_locator.1z5EI7G', 'get_ServiceLocator_1z5EI7GService.php', true),
    'App\\Controller\\Admin\\StatusController:edit' => array('privates', '.service_locator.1z5EI7G', 'get_ServiceLocator_1z5EI7GService.php', true),
    'App\\Controller\\Admin\\StatusController:index' => array('privates', '.service_locator.Hl4ShtN', 'get_ServiceLocator_Hl4ShtNService.php', true),
    'App\\Controller\\Admin\\TemplateController:add' => array('privates', '.service_locator.yT.jmqX', 'get_ServiceLocator_YT_JmqXService.php', true),
    'App\\Controller\\Admin\\TemplateController:delete' => array('privates', '.service_locator.6cK97Yc', 'get_ServiceLocator_6cK97YcService.php', true),
    'App\\Controller\\Admin\\TemplateController:edit' => array('privates', '.service_locator.9J1BkiM', 'get_ServiceLocator_9J1BkiMService.php', true),
    'App\\Controller\\Admin\\TemplateController:more' => array('privates', '.service_locator.6cK97Yc', 'get_ServiceLocator_6cK97YcService.php', true),
    'App\\Controller\\RegistrationController:register' => array('privates', '.service_locator.wyrb61.', 'get_ServiceLocator_Wyrb61_Service.php', true),
    'App\\Controller\\SecurityController:login' => array('privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true),
    'App\\Controller\\TemplateController:show' => array('privates', '.service_locator.6cK97Yc', 'get_ServiceLocator_6cK97YcService.php', true),
))), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
