<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\ProductServices\ProductBuilder' shared autowired service.

include_once $this->targetDirs[3].'/src/Services/ProductServices/ProductBuilder.php';

return $this->privates['App\Services\ProductServices\ProductBuilder'] = new \App\Services\ProductServices\ProductBuilder(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
