<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\TemplateServices\TemplateBuilder' shared autowired service.

include_once $this->targetDirs[3].'/src/Services/TemplateServices/TemplateBuilder.php';
include_once $this->targetDirs[3].'/src/Services/FileUploader.php';

return $this->privates['App\Services\TemplateServices\TemplateBuilder'] = new \App\Services\TemplateServices\TemplateBuilder(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), new \App\Services\FileUploader(($this->targetDirs[3].'/public/uploads/landing')));
