<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\PostService\PostFactory' shared autowired service.

include_once $this->targetDirs[3].'/src/Services/PostService/PostFactory.php';
include_once $this->targetDirs[3].'/src/Services/Converter.php';

return $this->privates['App\Services\PostService\PostFactory'] = new \App\Services\PostService\PostFactory(new \App\Services\Converter());
