<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQInjeoZ\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQInjeoZ/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQInjeoZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQInjeoZ\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerQInjeoZ\srcApp_KernelProdContainer(array(
    'container.build_hash' => 'QInjeoZ',
    'container.build_id' => '2c7d4c06',
    'container.build_time' => 1549096764,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQInjeoZ');
