<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1z5EI7G' shared service.

return $this->privates['.service_locator.1z5EI7G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'status' => array('privates', '.errored..service_locator.1z5EI7G.App\\Entity\\Status', NULL, 'Cannot autowire service ".service_locator.1z5EI7G": it references class "App\\Entity\\Status" but no such service exists.'),
));
