<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Zic7e68' shared service.

return $this->privates['.service_locator.Zic7e68'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'builder' => array('privates', 'App\\Services\\ProductServices\\ProductBuilder', 'getProductBuilderService.php', true),
));
