<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SNb0GSl' shared service.

return $this->privates['.service_locator.SNb0GSl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'builder' => array('privates', 'App\\Services\\OrderServices\\OrderBuilder', 'getOrderBuilderService.php', true),
    'template' => array('privates', '.errored..service_locator.SNb0GSl.App\\Entity\\Template', NULL, 'Cannot autowire service ".service_locator.SNb0GSl": it references class "App\\Entity\\Template" but no such service exists.'),
));
