<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ep7NscA' shared service.

return $this->privates['.service_locator.Ep7NscA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'builder' => array('privates', 'App\\Services\\OrderServices\\OrderBuilder', 'getOrderBuilderService.php', true),
    'mapper' => array('privates', 'App\\Services\\OrderServices\\OrderMapper', 'getOrderMapperService.php', true),
    'order' => array('privates', '.errored..service_locator.Ep7NscA.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.Ep7NscA": it references class "App\\Entity\\Order" but no such service exists.'),
));
