<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VNApzGZ' shared service.

return $this->privates['.service_locator.VNApzGZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'order' => array('privates', '.errored..service_locator.VNApzGZ.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.VNApzGZ": it references class "App\\Entity\\Order" but no such service exists.'),
));
