<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0dqscNU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0dqscNU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0dqscNU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0dqscNU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0dqscNU\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '0dqscNU',
    'container.build_id' => '9a6614a4',
    'container.build_time' => 1552050520,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0dqscNU');
